### ISSUE TITLE
Second Client Implementation

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/toolchain#32]
Implement a second client to accompany @web3api/client-js. This will prove that Web3APIs are in fact cross-platform.

**Comment by krisbitney** [comment]
I propose a Kotlin Client. Part of my motivation for proposing Kotlin is that I just like the language, so I am biased in its favor, but I think the business case for Kotlin is convincing on its own merit. I'll provide a brief overview.

**A Kotlin Client is a multi-language client**

Kotlin is designed with interoperability such that Client logic can be written once in Kotlin, and interfaces can then be written in C, C++, Objective C, Swift, Java, Kotlin, and/or Javascript. Kotlin can accomplish this because it compiles or transpiles to many targets, in a write-once-run-anywhere fashion. Among those targets are the major desktop and mobile operating systems, Apple and Android Internet of Things devices, JVM, Javascript (DOM and NodeJS), and WASM.

Because Kotlin can compile to WASM, it can also be used to write a Web3API. This is promising because it suggests developers could use a single language for writing, testing, and using their Web3APIs. However, Kotlin’s WASM compiler is still experimental. The Kotlin team decided to write a new WASM compiler backend from scratch due to garbage collection issues with the LLVM-based implementation Kotlin’s WASM compiler currently uses. They have written a prototype compiler, and are currently putting together a dedicated Kotlin/WASM team. It is not clear how long it will be before Kotlin’s new WASM compiler is ready.

A Kotlin Client quickly becomes a Multi-langauge Client, making Web3API available on mobile, desktop, and even IoT.

**Kotlin is performant**

Kotlin is fast. It performs comparatively well in the class of high-level, garbage-collected languages commonly used for application and web development, like Java, C#, and JavaScript. If we aren’t specifically targeting the game development market with our next Client, Kotlin’s performance and interoperability with C/C++ are favorable points of interest.

**Kotlin is a pleasure to use**

Kotlin is heavily influenced by languages such as TypeScript, offering many of the modern language features TypeScript developers love while arguably improving on some. Although my experience with Kotlin is limited, at one point I read almost the entirety of the Kotlin language documentation and used Kotlin while working through Google’s Android app development course. I’m not especially fond of JavaScript, but I enjoy using TypeScript and I think Kotlin offers the features that make TypeScript a pleasure to use.

The explicit goal of Kotlin is to be a better language than Java. Kotlin offers the good parts of Java—like its excellent Collections framework—while dropping the verbosity and rigidness that detract from productivity. Kotlin has high flexibility, expressive functional programming, an excellent asynchronous programming framework, annotations, null safety, type safety, syntax sugar like destructuring operators and single-line class declarations similar to TypeScript interfaces, and more.

Kotlin is open source, but its development is centralized. It’s developed by Jetbrains and directed by the nonprofit Kotlin Foundation, co-founded by Jetbrains and Google. It is also promoted by Google as the official language of Android. Importantly, it has a large community with extensive documentation.

**Comment by pwvpwvpwv** [comment]
We propose the next Polywrap client be implemented in Python, with Rust being a close second choice. We also think that there's some more work that needs to be done beyond picking an implementation language for a second client, to ensure Polywrap's continued growth beyond one or two languages; more on that below.

## Picking a Language
While there are many criteria by which one might pick an implementation language, we are of the opinion that early-stage projects like Polywrap would benefit most from targeting platforms that have a large user base and are experiencing solid growth. This ensures that the project has an opportunity to get as many eyeballs on it as possible, in order to grow its own community and to get the necessary feedback to advance the project in the right direction. In practical terms, it can be hard to directly gauge metrics like adoption friction and how accepting a community might be to new concepts, so Polywrap should be looking to implement their second client in a popular language whose community is showing an increased and/or growing interest in Web3-related applications, under the understanding that this will net them the widest and most diverse audience of potential adopters.

### Trends
Looking to see which language(s) Polywrap should target next, we consider the cumulative sum of Web3-related GitHub repositories (repos) over time, grouped by primary language.

![cumsum data](https://user-images.githubusercontent.com/66093127/151810408-3c9b634e-d4ad-4fd5-bd53-382a74ba78d7.png)

Here, we can see that Python, Rust, and Go are the three leading languages by number of public repos, with Java and PHP trailing not far behind. We can also see that, while C# seems to be breaking from the pack, the next five languages remain decidedly smaller in overall uptake, and can be considered in a separate category from the top-five previously mentioned.

Python and Go have strongly dominated the other languages for much of the time-frame, with Python seeing a recent jump of exponential growth starting near the end of 2020. However, despite this dominance, Rust has recently overtaken Go in terms of overall repo count; that being said, as the majority of Rust repos have appeared within the last 18-20 months they ostensibly lack the maturity and stability of similarly-classed Go repos.

![first derivative](https://user-images.githubusercontent.com/66093127/151810478-f1661cf5-20cb-4eab-9bd0-a8fe4a30e8d3.png)

This sudden increase in popularity can be better seen here, with Go's overall growth trends more closely matching those of the bottom half of the top-ten languages than the top half.

![second derivative](https://user-images.githubusercontent.com/66093127/151810561-68a30052-6cc9-4adc-84d7-7f0966a5e7bf.png)

In fact, Go's growth began to slow down starting in the third quarter of 2018, only regaining steam and accelerating starting in 2021, which may be attributed to overall trends of increased Web3 interest across the board, as reflected in the other languages.
Of note as well is Python's continuous acceleration since Q3 2020, reaching near exponential growth towards the end of 2021. This should be considered in contrast with Rust's growth, which actually began to slow down in the final quarter of 2021, potentially indicating a "fad" trend that may not keep pace after the initial interest wanes.

### Popularity Contest
Given these trends, I strongly believe Polywrap should consider Python for its next client implementation target, followed by either Rust or Go, as prioritized by either overall position and growth rate, or (potential) maturity and stability, respectively.

#### Aside: methodology
The data discussed above was collected from GitHub's search API using the query
```
web3 in:name,description,readme is:public archived:false
```
which selects for public, unarchived repos that contain the text "web3" somewhere in their name, description, or README file.
This data was collected for the range spanning from 2010 until now, and was further filtered to only include repos where GitHub had assigned a primary language, and that the primary language was not one of the following:
```py
[
    'JavaScript', 'TypeScript', 'HTML', 'CSS', 'Vue', 'Handlebars', 'SCSS', 'Svelte',  # web languages
    'Dockerfile', 'Shell',  # configuration and devops repos most often
    'Solidity',  # already meant to compile to the Ethereum VM
]
```

This data was then further reshaped: repos marked as primarily containing "Jupyter Notebook"s were subsumed into the "Python" category; because of the diversity of languages used and recognized by GitHub, the original selection (>100 languages) was pared down to just the top ten, so they could be better visualized; data before 2017 was removed for visualization and semantic reasons — all measured languages had < 100 repos, and "Web3" had not yet been widely adopted for the concept that it captures today, and was still mostly in use to describe the business connotation of "Web3" that preceded current popular usage.

The data plotted in the second and third charts are, respectively, first and second derivatives of the original data, resampled onto a quarterly timescale to reduce dithering and better show overarching trends.

Further information, such as operationalizing repo "activity" via "last-push" and "last-updated" dates, as well as open issue and discussion counts and user/contributor counts, can help to further inform Polywrap's decision with regards to subtler dimensions of interest, such as overall repo maturity, productivity, etc.

## A Different Question
Before we ask what to build next, we should first ask a more foundational question: “how do I build it?”; or, in different words, “how do I know that I've built the right thing?”. To that end, we propose a second effort that would go hand-in-hand with the first, to create a standard specification and test suite that can be used to determine both what to build against when drafting a new client, and whether a proposed client meets muster and should be adopted. The reason for both a specification and a test suite being that Polywrap clients are in effect a kind of **SDK**, having both an API component (the client code which we use to call queries and load wrappers), and a runtime component (the actual underlying implementation that loads and parses WASM and Polywrap-specific files, and executes the queries asked in the WASM).

#### Aside: prior art
Obviously the issue of maintaining multiple SDKs in different languages is not a new problem. Two good examples we'd like to point out seem to present a counterpoint to our earlier argument in favour of devoting effort to ensuring parity across implementations. The first of these is GitHub, which offers a traditional SDK experience for their REST API: they offer three "official" SDKs, one each for Ruby, .NET, and JavaScript, and then separately list "third-party libraries" grouped by language. The second case is that of Apache BEAM, which offers a set of "supported" SDKs and runners which live in the BEAM repo, and links to their public JIRA for suggesting new SDKs/runners.

In both these cases, the parent organization provides "official" implementations and offers a mechanism for "unofficial" implementations to be showcased/discussed. However, these two approaches both seem to have their downsides: GitHub takes a laissez-faire approach and simply says, "here are some other implementations that we didn't check, caveat emptor", which allows for many different (and potentially competing) implementations at the cost of end-user clarity -- the unofficial SDKs seem less trustworthy as they are distanced from the brand -- and surety; Apache BEAM, on the other hand, seems to promise functionality and trustworthiness of their official SDKs, at the cost of having a bureaucratic and potentially opaque system for promulgating new SDKs/runners, which we can see in their paltry offering of three different languages to GitHub's combined 19 official and unofficial language offerings. These two cases present an interesting third alternative, where we believe Polywrap's decentralization will shine brightest: by creating a toolset to *verify*\* potential SDKs, Polywrap can eliminate the opacity of BEAM's approach while still being able to offer a "stamp of approval" for any submitted SDKs that have passed the necessary tests.

### An API specification
In general, the problem of maintaining clients across several languages and preventing drift is usually solved by defining a single API spec and then building to that spec (or generating clients against the spec using tools like Swagger or APImatic). However, generated clients/SDKs often require additional work, and the generators themselves need sophisticated tuning in the appropriate language in order to output effective code \[1\].

For reference, the current JS/TS client has the following API:
```ts
interface Web3ApiClient extends Client {
    setTracingEnabled(enable: boolean): void;
    getRedirects(options: GetRedirectsOptions): readonly UriRedirect<Uri>[];
    getPlugins(options: GetPluginsOptions): readonly PluginRegistration<Uri>[];
    getInterfaces(options: GetInterfacesOptions): readonly InterfaceImplementations<Uri>[];
    getEnvs(options: GetEnvsOptions): readonly Env<Uri>[];
    getEnvByUri<TUri extends Uri | string>(uri: TUri, options: GetEnvsOptions): Env<Uri> | undefined;
    async getSchema<TUri extends Uri | string>(uri: TUri, options: GetSchemaOptions): Promise<string>;
    async getManifest<TUri extends Uri | string, TManifestType extends ManifestType>(uri: TUri, options: GetManifestOptions): Promise<AnyManifest<TManifestType>>;
    async getFile<TUri extends Uri | string>(uri: TUri, options: GetFileOptions): Promise<string | ArrayBuffer>;
    getImplementations<TUri extends Uri | string>(uri: TUri, options: GetImplementationsOptions): TUri[];
    async query<TData extends Record<string, unknown> = Record<string, unknown>, TVariables extends Record<string, unknown> = Record<string, unknown>, TUri extends Uri | string = string>(options: QueryApiOptions<TVariables, TUri, Web3ApiClientConfig>): Promise<QueryApiResult<TData>>;
    async invoke<TData = unknown, TUri extends Uri | string = string>(options: InvokeApiOptions<TUri, Web3ApiClientConfig>): Promise<InvokeApiResult<TData>>;
    subscribe<TData extends Record<string, unknown> = Record<string, unknown>, TVariables extends Record<string, unknown> = Record<string, unknown>, TUri extends Uri | string = string>(options: SubscribeOptions<TVariables, TUri, Web3ApiClientConfig>): Subscription<TData>;
}
```

One direct approach Polywrap could take would be to codify this existing API is some language-agnostic API specification format, and to then use that spec as a template to confirm all other clients against. Any updates to the spec would then need to be reflected in the various clients/SDKs, who would need to meet the appropriate API "version", as centralized in the spec. This centralization effort would effectively prevent the common issue organizations experience, where certain SDKs in a particular language are better than SDKs in other languages, and therefore gain more traction and force prospective users to adopt that particular language over their preferred one. Further, a potential benefit of centralization is that it would allow for Polywrap, should they choose to implement an in-house generator à la \[1\], to ensure quick and stable updates to all SDKs whenever an update is made to the API spec. In general, it may be prudent to follow the advice of \[2\] (or similar) and to attempt to reap the rewards of automation that can be gained from a single source of truth specification.

### A Test Suite
With the API aspect of the SDKs covered, we should next consider the runtime component. In order to test that a proposed SDK has correctly implemented the expected WASM runtime behaviour, Polywrap should put together a list of wrappers, query recipes, and easily translatable code snippets, and their expected "correct" results and side effects. That way, a suite of tests can be run against any SDK (even ones that have already been ok'd but may have been updated or improved) and the outputs and resulting state can be compared against known good values. This will give both Polywrap and its users a way to make sure that a given SDK is working as expected, independent of whether it has all of the expected methods and functions and bells and whistles that are expected.
While the rise of paradigms like Test Driven Development may be a bit ideological for wide public adoption, we believe that the concept of functional and unit testing of this sort is a well-understood and well-regarded one that will make sense to SDK maintainers and builders alike. Having these tests be public and obvious will also lower the barrier to entry and development friction that any SDK builders may experience, allowing Polywrap to benefit from its open source community by empowering its members with the tools they need to make the SDKs they want to use.

#### A final footnote on \*"verification"
For a bit of context, usually when people talk about "verification" in the context of things like programming languages and compilers, they mean formal verification, involving logic and theorem provers, the whole shebang. We believe that that level of rigour is neither expected of nor needed for the Polywrap project: the early adopters of Polywrap are likely to be less concerned with the theoretical bounds of the Polywrap client/runtime (which will likely be changing and updating as Polywrap exits alpha, then beta) than they are with the more practical issues of usability and feature-completeness. Devs will want clients that "just work" and that are in their preferred language so they can integrate with other parts of their dApp with ease; they won't necessarily be looking for mathematical proof that their dApp is sound. Because of this we believe that approximating verification in an empirical way makes more sense for the project at this time, with the added benefit that having a library of clear, obvious examples of code/recipes and expected results can be an incredible learning and documentation resource for Polywrap's users.

## References
 1. Murphy, L., Kery, M. B., Alliyu, O., Macvean, A., & Myers, B. A. (2018, October). API designers in the field: Design practices and challenges for creating usable APIs. In 2018 ieee symposium on visual languages and human-centric computing (vl/hcc) (pp. 249-258). IEEE.
 2. Thomas, E. (2017). *Supporting SDKs in Seven Different Languages While Maintaining Sanity* \[conference presentation\]. DevRelCon 2017, London, UK. <https://youtu.be/rONq4nKxy1A>.

**Comment by evanjacobs** [comment]
@pwvpwvpwv Thanks for the detailed write up! I appreciate the thought that you've put into not just selecting the next client implementation but also how to generalize for N clients and keeping them in sync as the API spec evolves.
